<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FLDMD95" name="com.redmine.tests.TestLogin" tests="6" failures="1" timestamp="20 Sep 2016 17:30:06 GMT" time="37.874" errors="0">
  <testcase name="testFirstFormPresent" time="3.355" classname="com.redmine.tests.TestLogin"/>
  <testcase name="testTextErrorFirstForm" time="2.768" classname="com.redmine.tests.TestLogin"/>
  <testcase name="testTextFirstForm" time="2.724" classname="com.redmine.tests.TestLogin"/>
  <testcase name="testTwoFormPresent" time="6.552" classname="com.redmine.tests.TestLogin"/>
  <testcase name="testAddQuestion" time="14.040" classname="com.redmine.tests.TestLogin"/>
  <testcase name="testTextErrorTwoForm" time="8.435" classname="com.redmine.tests.TestLogin">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.redmine.tests.TestLogin.testTextErrorTwoForm(TestLogin.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- testTextErrorTwoForm -->
</testsuite> <!-- com.redmine.tests.TestLogin -->
